[data]
path = "resources/Terrains/valley_and_peak.png"
render_size = 20.0
render_height = 20.0

[lights]
positions = [[8.0, 5.0, 0.0]]
colors = [[1.0, 1.0, 1.0]]

[camera]
look_at = [0.0, 0.0, -1.0]
rotations = [0.0, 0.0, 0.0]
dist = 10.0

[gradient]
paths = ["resources/ColorMaps/inferno.png",
		 "resources/ColorMaps/magma.png",
		 "resources/ColorMaps/plasma.png",
		 "resources/ColorMaps/rainbow.png",
		 "resources/ColorMaps/viridis.png"]
