[data]
path = "resources/Montains-16.png"
render_size = 20.0
render_height = 20.0

[lights]
positions = [[8.0, 5.0, 0.0]]
colors = [[0.9, 0.9, 0.9]]

[camera]
lookAt = [0.0, 0.0, -1.0]
rotations = [0.0, 0.0, 0.0]
dist = 10.0
fovy = 50.0

